import {
	ICON_SIMULATOR_MODULE,
	ICON_SCHEDULER_MODULE,
	ICON_BUSINESS_OPPORTUNITIES,
	ICON_LANDING_MODULE,
	ICON_RESERVATION_MODULE,
	ICON_CREDITS_MODULE,
	ICON_REPORTS_MODULE,
	ICON_CONTACT_REQUEST,
	ICON_BUSINESS_MODULE,
	ICON_BUYER_NOTIFICATIONS,
	ICON_COTIZADOR,
} from './icons';

export const SUITE_MODULES = {
	SIMULATOR_MODULE: 'gestor_de_inventarios',
	SCHEDULER_MODULE: 'agendador',
	LANDING_BUILDER_MODULE: 'landing_builder',
	BUSINESS_OPPORTUNITIES: 'oportunidades_de_negocio',
	RESERVATION: 'reservas',
	CREDITS: 'creditos_hipotecarios',
	REPORTS: 'reportes',
	CONTACT_REQUEST: 'solicitudes_de_contacto',
	BUSINESS_MODULE: 'negocios',
	BUYER_NOTIFICATIONS: 'notificaciones_a_compradores',
	COTIZADOR: 'cotizador',
};

export const MODULE_ICONS = {
	[SUITE_MODULES.SIMULATOR_MODULE]: ICON_SIMULATOR_MODULE,
	[SUITE_MODULES.SCHEDULER_MODULE]: ICON_SCHEDULER_MODULE,
	[SUITE_MODULES.LANDING_BUILDER_MODULE]: ICON_LANDING_MODULE,
	[SUITE_MODULES.BUSINESS_OPPORTUNITIES]: ICON_BUSINESS_OPPORTUNITIES,
	[SUITE_MODULES.RESERVATION]: ICON_RESERVATION_MODULE,
	[SUITE_MODULES.CREDITS]: ICON_CREDITS_MODULE,
	[SUITE_MODULES.REPORTS]: ICON_REPORTS_MODULE,
	[SUITE_MODULES.CONTACT_REQUEST]: ICON_CONTACT_REQUEST,
	[SUITE_MODULES.BUSINESS_MODULE]: ICON_BUSINESS_MODULE,
	[SUITE_MODULES.BUYER_NOTIFICATIONS]: ICON_BUYER_NOTIFICATIONS,
	[SUITE_MODULES.COTIZADOR]: ICON_COTIZADOR,
};

export default {};
