export const COMMERCIAL_OPPORTUNITIES = {
	INTERESTED: 'interested',
	VISITED: 'visited',
	RESERVED_OR_SEPARATED: 'reserved_or_separated',
	DISCARDED: 'discarded',
};

export const COMMERCIAL_OPPORTUNITIES_COLORS = {
	[COMMERCIAL_OPPORTUNITIES.RESERVED_OR_SEPARATED]: 'success',
	[COMMERCIAL_OPPORTUNITIES.DISCARDED]: 'error',
	[COMMERCIAL_OPPORTUNITIES.INTERESTED]: 'primary',
	[COMMERCIAL_OPPORTUNITIES.VISITED]: 'primary',
};

export const PARSE_COMMERCIAL_OPPORTUNITIES = {
	[COMMERCIAL_OPPORTUNITIES.RESERVED_OR_SEPARATED]: 'title_reserved_or_separated',
	[COMMERCIAL_OPPORTUNITIES.VISITED]: 'title_visited',
	[COMMERCIAL_OPPORTUNITIES.INTERESTED]: 'title_interested',
	[COMMERCIAL_OPPORTUNITIES.DISCARDED]: 'title_discarded',
};

export default {};
